services:
  ticket94_fastapi_db:
    container_name: ticket94_fastapi_db
    image: postgres:16
    command: postgres -c 'max_connections=250'
    restart: always
    env_file:
      - ./env/.env.db
    volumes:
      - ./data/postgresql_data:/var/lib/postgresql/data # 資料庫docker刪掉，會備份
    ports:
      - "7000:5432"

  ticket94_fastapi_backend:
    container_name: ticket94_fastapi_backend
    build:
      context: .   # 專案根目錄
      dockerfile: Dockerfile
    restart: always
    ports:
      - "7001:8000"
    env_file:
      - ./env/.env
    depends_on:
      - ticket94_fastapi_db 

