"""create seat related tables

Revision ID: a81055d52ee9
Revises: b5bc335f7a8e
Create Date: 2025-06-13 18:03:24.709093

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a81055d52ee9"
down_revision: str | None = "b5bc335f7a8e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("order_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("order_number", sa.String(length=30), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PAID", "CANCELED", "EXPIRED", name="orderstatus"),
            nullable=False,
        ),
        sa.Column(
            "payment_method",
            sa.Enum("CREDIT_CARD", "IBON", "LINE_PAY", name="paymentmethod"),
            nullable=True,
        ),
        sa.Column("total_amount", sa.Float(), nullable=False),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.event_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("order_id"),
        sa.UniqueConstraint("order_number"),
    )
    op.create_table(
        "order_items",
        sa.Column("order_item_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("ticket_type_id", sa.Integer(), nullable=False),
        sa.Column("seat_id", sa.Integer(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.order_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["seat_id"], ["seats.seat_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["ticket_type_id"],
            ["event_ticket_types.ticket_type_id"],
        ),
        sa.PrimaryKeyConstraint("order_item_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_items")
    op.drop_table("orders")
    # ### end Alembic commands ###
