"""create seat related tables

Revision ID: b5bc335f7a8e
Revises: 535ee6749e6c
Create Date: 2025-06-13 17:45:23.074120

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5bc335f7a8e"
down_revision: str | None = "535ee6749e6c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sections",
        sa.Column("section_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("ticket_type_id", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.event_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["ticket_type_id"],
            ["event_ticket_types.ticket_type_id"],
        ),
        sa.PrimaryKeyConstraint("section_id"),
    )
    op.create_table(
        "seating_rows",
        sa.Column("row_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("row_name", sa.String(length=10), nullable=False),
        sa.Column("row_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["section_id"], ["sections.section_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("row_id"),
    )
    op.create_table(
        "seats",
        sa.Column("seat_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("row_id", sa.Integer(), nullable=False),
        sa.Column("seat_number", sa.String(length=10), nullable=False),
        sa.Column(
            "status", sa.Enum("VACANT", "TEMP_HOLD", "RESERVED", name="seatstatus"), nullable=False
        ),
        sa.Column("hold_expires_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["row_id"], ["seating_rows.row_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("seat_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("seats")
    op.drop_table("seating_rows")
    op.drop_table("sections")
    # ### end Alembic commands ###
