"""Add SOLD to SeatStatus

Revision ID: 7a1493d5d425
Revises: a81055d52ee9
Create Date: 2025-06-24 17:26:19.210588

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a1493d5d425"
down_revision: str | None = "a81055d52ee9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE seatstatus ADD VALUE 'S';")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
