"""remove sqlEnum

Revision ID: 98b43c6a0e0b
Revises: 7a1493d5d425
Create Date: 2025-06-24 17:49:17.047894

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98b43c6a0e0b"
down_revision: str | None = "7a1493d5d425"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "status",
        existing_type=postgresql.ENUM("PENDING", "PAID", "CANCELED", "EXPIRED", name="orderstatus"),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "payment_method",
        existing_type=postgresql.ENUM("CREDIT_CARD", "IBON", "LINE_PAY", name="paymentmethod"),
        type_=sa.String(length=20),
        nullable=False,
    )
    op.alter_column(
        "seats",
        "status",
        existing_type=postgresql.ENUM("VACANT", "TEMP_HOLD", "RESERVED", "S", name="seatstatus"),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "seats",
        "status",
        existing_type=sa.String(length=20),
        type_=postgresql.ENUM("VACANT", "TEMP_HOLD", "RESERVED", "S", name="seatstatus"),
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "payment_method",
        existing_type=sa.String(length=20),
        type_=postgresql.ENUM("CREDIT_CARD", "IBON", "LINE_PAY", name="paymentmethod"),
        nullable=True,
    )
    op.alter_column(
        "orders",
        "status",
        existing_type=sa.String(length=20),
        type_=postgresql.ENUM("PENDING", "PAID", "CANCELED", "EXPIRED", name="orderstatus"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
