"""add is_deleted to event

Revision ID: 38478a028e97
Revises: a6aa1d5b20d4
Create Date: 2025-02-17 13:52:03.036132

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38478a028e97"
down_revision: Union[str, None] = "a6aa1d5b20d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "is_deleted")
    # ### end Alembic commands ###
