"""rm role in user table

Revision ID: bc24e1e51051
Revises: 0912ac932b6d
Create Date: 2025-02-13 11:44:22.443689

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc24e1e51051"
down_revision: Union[str, None] = "0912ac932b6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("role", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
